import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import ReduxProvider from "@/store/ReduxProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className="bg-[#ffffff]">
          <Header />
          {/* <Index /> */}
          <main className="min-h-[100vh]">{children}</main>
          <Footer />
        </body>
      </html>
    </ReduxProvider>
  );
}
